### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by donnerc** [informatiquecsud/OnlinePythonTutor#2]
# Description

Currently, the UX is far from ideal, especially for large programs. To improve the debugging experience, the following elements have to be improved:

## TODO

- [x] Enlarge the left pane with the code for it to be visible entirely. The width could be adapted according to the length of the longest code line for instance, up to a certain threshold.
- [ ] Some more options should be configurable through HTTP request parameters
- [ ] Add shortcuts to navigate through the steps with key press P = previous / N = next / S = Start / E = End

## Postponed

- In iframe mode, move the controls (previous / next / ...) to the top of the visualization, in order for them to stay visible, even when the code is large -> Not possible for now ... breaks the slider and controls because of the spaghetti jquery code.
